import { describe, it, expect } from 'vitest'
import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { runExport } from '../export-pipeline.js'

// Round-trip test with the REAL demo fixtures (public/demo, generated by
// scripts/make-demo-media.sh): keyframed 360 reframe exports must show the
// same ground truth the WebGL preview pixel-probes verified —
//   pan=0   → FRONT (whitish stripe over blue bg)
//   pan=180 → BACK  (plain blue bg)
const DEMO = path.resolve(__dirname, '../public/demo')
const FFMPEG = '/opt/homebrew/bin/ffmpeg'

function centerPixelRgb(file, t) {
  const buf = execFileSync(
    FFMPEG,
    [
      '-loglevel', 'error',
      '-ss', String(t),
      '-i', file,
      '-vf', 'crop=8:8:iw/2:ih/2,format=rgb24',
      '-frames:v', '1',
      '-vcodec', 'rawvideo', '-pix_fmt', 'rgb24', '-f', 'rawvideo', '-',
    ],
    { stdio: ['ignore', 'pipe', 'ignore'], maxBuffer: 1024 * 1024 }
  )
  let r = 0, g = 0, b = 0
  const n = buf.length / 3
  for (let i = 0; i < buf.length; i += 3) {
    r += buf[i]; g += buf[i + 1]; b += buf[i + 2]
  }
  return [Math.round(r / n), Math.round(g / n), Math.round(b / n)]
}

const eqPath = path.join(DEMO, 'demo-equirect.mp4')
const dfPath = path.join(DEMO, 'demo-dfisheye.mp4')

describe('demo-video export round-trip (preview ≈ export)', () => {
  const TMP = fs.mkdtempSync(path.join(os.tmpdir(), 'aero-demo-rt-'))

  it('equirect keyframed pan 0→180 exports FRONT then BACK views', { timeout: 120_000 }, async () => {
    const out = path.join(TMP, 'eq-pan.mp4')
    const res = await runExport({
      outputPath: out,
      width: 960,
      height: 540,
      fps: 24,
      videoTracks: [
        {
          clips: [
            {
              kind: 'video',
              path: eqPath,
              position: 0,
              trimIn: 0,
              duration: 4,
              is360: true,
              projection: 'equirect',
              keyframes: [
                { id: 'a', time: 0.2, pan: 0, tilt: 0, roll: 0, fov: 90, easing: 'linear' },
                { id: 'b', time: 3.8, pan: 180, tilt: 0, roll: 0, fov: 90, easing: 'linear' },
              ],
            },
          ],
        },
      ],
      musicClips: [],
    })
    expect(res.ok).toBe(true)

    const start = centerPixelRgb(out, 0.4)
    const end = centerPixelRgb(out, 3.6)
    // FRONT at pan=0: whitish stripe → all channels high, near-neutral
    expect(start[0]).toBeGreaterThan(110)
    expect(start[1]).toBeGreaterThan(110)
    expect(start[2]).toBeGreaterThan(110)
    // BACK at pan=180: plain bg #2a5d8f → blue dominant
    expect(end[2] - end[0]).toBeGreaterThan(30)
    // and the two views genuinely differ
    expect(Math.abs(start[0] - end[0])).toBeGreaterThan(30)
  })

  it('dfisheye keyframed pan 0→180 exports FRONT then BACK views', { timeout: 120_000 }, async () => {
    const out = path.join(TMP, 'df-pan.mp4')
    const res = await runExport({
      outputPath: out,
      width: 960,
      height: 540,
      fps: 24,
      videoTracks: [
        {
          clips: [
            {
              kind: 'video',
              path: dfPath,
              position: 0,
              trimIn: 0,
              duration: 4,
              is360: true,
              projection: 'dfisheye',
              lensFov: 220,
              keyframes: [
                { id: 'a', time: 0.2, pan: 0, tilt: 0, roll: 0, fov: 90, easing: 'linear' },
                { id: 'b', time: 3.8, pan: 180, tilt: 0, roll: 0, fov: 90, easing: 'linear' },
              ],
            },
          ],
        },
      ],
      musicClips: [],
    })
    expect(res.ok).toBe(true)

    const start = centerPixelRgb(out, 0.4)
    const end = centerPixelRgb(out, 3.6)
    // FRONT lens centre = whitish stripe
    expect(start[0]).toBeGreaterThan(110)
    expect(start[1]).toBeGreaterThan(110)
    expect(start[2]).toBeGreaterThan(110)
    // BACK = blue bg
    expect(end[2] - end[0]).toBeGreaterThan(30)
    expect(Math.abs(start[0] - end[0])).toBeGreaterThan(30)
  })
})
